import CryptoKit
import Foundation
import Security
import UIKit
import UniformTypeIdentifiers

/// Cipher shared with the main app's HermesIntentQueueCipher. The key lives
/// in the shared Keychain access group when the entitlement is present and
/// is mirrored into the plain (no access group) item so resign-compatible
/// builds — where one side may lack the group entitlement — still decrypt
/// each other's payloads.
private enum HermesShareCipherError: Error {
  case keyUnavailable
}

private enum HermesShareQueueCipher {
  private static let service = "app.hermes.intent-queue"
  private static let account = "payload-key-v1"

  static func seal(_ entry: [String: Any]) -> Data? {
    guard JSONSerialization.isValidJSONObject(entry),
          let clear = try? JSONSerialization.data(withJSONObject: entry),
          let key = try? key(),
          let encrypted = try? AES.GCM.seal(clear, using: key),
          let combined = encrypted.combined else { return nil }
    return combined
  }

  /// Throws on any key-management failure — the queue is fail-closed: a
  /// zero key or an unwritten temp key would silently downgrade every sealed
  /// payload, so the caller drops the share instead of encrypting weakly.
  private static func key() throws -> SymmetricKey {
    if let existing = readKey(), existing.count == 32 {
      return SymmetricKey(data: existing)
    }
    var bytes = Data(count: 32)
    guard SecRandomCopyBytes(kSecRandomDefault, 32, &bytes) == errSecSuccess else {
      throw HermesShareCipherError.keyUnavailable
    }
    if let accessGroup = sharedAccessGroup() {
      var insert = selector(accessGroup: accessGroup)
      insert[kSecValueData as String] = bytes
      insert[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
      let status = SecItemAdd(insert as CFDictionary, nil)
      if status != errSecSuccess && status != errSecDuplicateItem {
        throw HermesShareCipherError.keyUnavailable
      }
    }
    // Mirror the same bytes into the plain item so a process without the
    // group entitlement can still open envelopes sealed here. A mirror
    // failure is non-fatal as long as the primary item landed.
    var plain = selector(accessGroup: nil)
    plain[kSecValueData as String] = bytes
    plain[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
    SecItemAdd(plain as CFDictionary, nil)
    // Trust freshly generated bytes only when they are durably retrievable.
    guard let stored = readKey(), stored.count == 32 else {
      throw HermesShareCipherError.keyUnavailable
    }
    return SymmetricKey(data: stored)
  }

  private static func readKey() -> Data? {
    for accessGroup in [sharedAccessGroup(), nil] {
      var query = selector(accessGroup: accessGroup)
      query[kSecMatchLimit as String] = kSecMatchLimitOne
      query[kSecReturnData as String] = true
      var result: CFTypeRef?
      if SecItemCopyMatching(query as CFDictionary, &result) == errSecSuccess,
         let data = result as? Data, data.count == 32 {
        return data
      }
    }
    return nil
  }

  private static func selector(accessGroup: String?) -> [String: Any] {
    var selector: [String: Any] = [
      kSecClass as String: kSecClassGenericPassword,
      kSecAttrService as String: service,
      kSecAttrAccount as String: account,
    ]
    if let accessGroup, !accessGroup.isEmpty, !accessGroup.contains("$(") {
      selector[kSecAttrAccessGroup as String] = accessGroup
    }
    return selector
  }

  private static func sharedAccessGroup() -> String? {
    guard let value = Bundle.main.object(forInfoDictionaryKey: "HermesSharedKeychainAccessGroup") as? String,
          !value.isEmpty,
          !value.contains("$(") else { return nil }
    return value
  }
}

final class ShareViewController: UIViewController {
  // viewDidAppear can fire twice (stacked presentation, dismissal animations);
  // without the guard one share sheet produced two spool entries.
  private var isProcessing = false
  private static let appGroup = "group.app.sunstone1029.fig1171.hermes"
  private static let attachmentsDirectory = "agent-share-attachments-v1"
  // Each share becomes one individually sealed spool file. Append-only file
  // creation replaces the legacy read-modify-write UserDefaults array, so the
  // extension, App Intents, and the main app can enqueue concurrently without
  // any cross-process lock; the main app binds and consumes files on drain.
  private static let spoolDirectory = "agent-trigger-inbox-v3"
  // Keep in lock-step with the JS drain (IOSContextProvider processes only
  // 10): staging more than the consumer uploads silently dropped attachments
  // 11-20 and left their app-group copies orphaned forever.
  private static let maxItems = 10
  private static let maxBytes = 50 * 1024 * 1024

  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    guard !isProcessing else { return }
    isProcessing = true
    process()
  }

  private func process() {
    let providers = (extensionContext?.inputItems as? [NSExtensionItem] ?? []).flatMap { $0.attachments ?? [] }
    let group = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Self.appGroup)
    let root = group?.appendingPathComponent(Self.attachmentsDirectory, isDirectory: true)
    if let root { try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true) }
    let work = DispatchGroup()
    let lock = NSLock()
    var entries: [[String: Any]] = []
    var totalBytes = 0
    for provider in providers.prefix(Self.maxItems) {
      work.enter()
      load(provider: provider, root: root) { entry, bytes in
        lock.lock(); defer { lock.unlock() }
        if let entry, entries.count < Self.maxItems, totalBytes + bytes <= Self.maxBytes {
          entries.append(entry); totalBytes += bytes
        } else if let filename = entry?["attachmentPath"] as? String, let root {
          // A rejected attachment has already been copied out of the
          // provider's temporary sandbox. Remove it immediately so repeated
          // oversized shares cannot fill the App Group container.
          try? FileManager.default.removeItem(at: root.appendingPathComponent(filename))
        }
        work.leave()
      }
    }
    work.notify(queue: .main) { [weak self] in
      self?.enqueue(entries: entries)
      self?.extensionContext?.completeRequest(returningItems: nil)
    }
  }

  private func load(provider: NSItemProvider, root: URL?, completion: @escaping ([String: Any]?, Int) -> Void) {
    let requestID = UUID().uuidString.lowercased()
    if provider.hasItemConformingToTypeIdentifier(UTType.plainText.identifier) {
      provider.loadFileRepresentation(forTypeIdentifier: UTType.plainText.identifier) { temporaryURL, _ in
        guard let temporaryURL else { completion(nil, 0); return }
        // Stream only the head of the file. loadDataRepresentation loaded
        // the WHOLE item into memory before prefix() could truncate, so a
        // multi-hundred-MB .txt blew the extension's ~120MB cap and the
        // jetsammed share failed silently with nothing enqueued.
        let maxTextBytes = 1_048_576
        guard
          let handle = try? FileHandle(forReadingFrom: temporaryURL),
          var head = try? handle.read(upToCount: maxTextBytes)
        else { completion(nil, 0); return }
        try? handle.close()
        // A 1MB read can split a multi-byte UTF-8 scalar at the boundary;
        // shed trailing continuation bytes so the decode still succeeds.
        var text = String(data: head, encoding: .utf8)?
          .trimmingCharacters(in: .whitespacesAndNewlines)
        if text == nil, head.count > 3 {
          head.removeLast(3)
          text = String(data: head, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        let trimmed = text ?? ""
        completion(trimmed.isEmpty ? nil : ["content": String(trimmed.prefix(20_000)), "kind": "analyze-text", "requestID": requestID, "createdAt": Date().timeIntervalSince1970 * 1000], trimmed.utf8.count)
      }
      return
    }
    if provider.hasItemConformingToTypeIdentifier(UTType.url.identifier) {
      provider.loadItem(forTypeIdentifier: UTType.url.identifier, options: nil) { item, _ in
        let url = (item as? URL)?.absoluteString ?? (item as? String) ?? ""
        completion(url.isEmpty ? nil : ["content": String(url.prefix(8_000)), "kind": "analyze-text", "requestID": requestID, "createdAt": Date().timeIntervalSince1970 * 1000], url.utf8.count)
      }
      return
    }
    // The plain-text and URL branches above already returned; this is the
    // file-representation fallback for images/movies/arbitrary items.
    let type: UTType = provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) ? .image : provider.hasItemConformingToTypeIdentifier(UTType.movie.identifier) ? .movie : .item
    provider.loadFileRepresentation(forTypeIdentifier: type.identifier) { temporaryURL, _ in
      guard let temporaryURL, let root else { completion(nil, 0); return }
      let accessed = temporaryURL.startAccessingSecurityScopedResource()
      defer { if accessed { temporaryURL.stopAccessingSecurityScopedResource() } }
      guard let values = try? temporaryURL.resourceValues(forKeys: [.fileSizeKey]), let size = values.fileSize, size <= Self.maxBytes else { completion(nil, 0); return }
      let safeName = temporaryURL.lastPathComponent.replacingOccurrences(of: "/", with: "_").prefix(120)
      let filename = "\(requestID)-\(safeName.isEmpty ? "attachment" : String(safeName))"
      let destination = root.appendingPathComponent(filename)
      do {
        try FileManager.default.copyItem(at: temporaryURL, to: destination)
        completion(["attachmentID": requestID, "attachmentPath": filename, "filename": String(safeName), "kind": "attachment", "requestID": requestID, "createdAt": Date().timeIntervalSince1970 * 1000], size)
      } catch { completion(nil, 0) }
    }
  }

  private func enqueue(entries: [[String: Any]]) {
    guard !entries.isEmpty else { return }
    let text = entries.compactMap { $0["content"] as? String }.joined(separator: "\n\n").trimmingCharacters(in: .whitespacesAndNewlines)
    let attachments = entries.filter { ($0["kind"] as? String) == "attachment" }
    var merged: [String: Any] = [
      "content": String(text.prefix(20_000)),
      "kind": "analyze-text",
      "requestID": UUID().uuidString.lowercased(),
      "createdAt": Date().timeIntervalSince1970 * 1000,
      "attachments": attachments,
    ]
    // Bind the share to the account the main app recorded at sign-in. The
    // extension cannot reach auth state itself; without a hint the entry
    // stays unbound and the main app DROPS it — never first-reader claims.
    let defaults = UserDefaults(suiteName: Self.appGroup) ?? .standard
    if let hint = defaults.dictionary(forKey: "agent-trigger-owner-hint"),
       let owner = hint["ownerScope"] as? String,
       let generation = hint["accountGeneration"] as? String,
       !owner.isEmpty, !generation.isEmpty {
      merged["ownerScope"] = owner
      merged["accountGeneration"] = generation
    }
    guard let envelope = HermesShareQueueCipher.seal(merged),
          let group = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Self.appGroup) else { return }
    let spool = group.appendingPathComponent(Self.spoolDirectory, isDirectory: true)
    do {
      try FileManager.default.createDirectory(at: spool, withIntermediateDirectories: true)
      // One sealed file per request; a unique name plus the atomic write
      // make concurrent producers safe without any shared mutable state.
      let target = spool.appendingPathComponent("\(UUID().uuidString.lowercased()).bin")
      try envelope.write(to: target, options: [.atomic])
    } catch {
      // A failed spool write drops this share request rather than falling
      // back to the plaintext legacy key: silently downgrading the queue's
      // confidentiality is never the right recovery.
    }
  }
}
