# Generated by scripts/generate-swiftui-route-actions.mjs. Do not edit.
from __future__ import annotations

from typing import Final, TypeGuard

SCHEMA_VERSION: Final = 1
SNAPSHOT_FIELDS: Final = (
    "version",
    "route",
    "sessions",
    "sessionContext",
    "files",
    "workflows",
    "approvals",
    "runtime",
    "analytics",
    "models",
    "modelConfirmation",
    "detectedModels",
    "operation",
    "logs",
    "cron",
    "skills",
    "integrations",
    "installations",
    "pairing",
    "achievements",
    "collaboration",
    "kanban",
    "profiles",
    "config",
    "environment",
    "system",
)
ACTION_PAYLOAD_FIELDS: Final = {
    "route": ("string", True),
    "id": ("string", False),
    "name": ("string", False),
    "value": ("string", False),
    "detail": ("string", False),
    "targetId": ("string", False),
    "enabled": ("boolean", False),
    "position": ("integer", False),
    "requestId": ("string", False),
    "fields": ("stringMap", False),
    "uris": ("stringArray", False),
}
ACTIONS: Final = {
    "refresh": "route.refresh",
    "sessionSelect": "session.select",
    "sessionOpen": "session.open",
    "sessionDelete": "session.delete",
    "sessionRename": "session.rename",
    "sessionCompress": "session.compress",
    "sessionFork": "session.fork",
    "fileSelect": "file.select",
    "fileDelete": "file.delete",
    "fileDownload": "file.download",
    "fileShare": "file.share",
    "fileImport": "file.import",
    "folderCreate": "folder.create",
    "modelSelect": "model.select",
    "modelSelectCancel": "model.select.cancel",
    "modelDiscover": "model.discover",
    "modelSave": "model.save",
    "modelTest": "model.test",
    "logsFilter": "logs.filter",
    "cronCreate": "cron.create",
    "cronToggle": "cron.toggle",
    "cronRun": "cron.run",
    "cronDelete": "cron.delete",
    "skillCreate": "skill.create",
    "skillToggle": "skill.toggle",
    "skillSelect": "skill.select",
    "skillView": "skill.view",
    "skillUpdate": "skill.update",
    "installationRollback": "installation.rollback",
    "pluginRescan": "plugin.rescan",
    "pluginInstall": "plugin.install",
    "pluginUpdate": "plugin.update",
    "pluginDelete": "plugin.delete",
    "pluginVisibility": "plugin.visibility",
    "integrationCreate": "integration.create",
    "integrationUpdate": "integration.update",
    "integrationToggle": "integration.toggle",
    "integrationDelete": "integration.delete",
    "mcpTest": "mcp.test",
    "mcpCatalogInstall": "mcp.catalog.install",
    "pairingApprove": "pairing.approve",
    "pairingRevoke": "pairing.revoke",
    "pairingClearPending": "pairing.clear-pending",
    "achievementsRescan": "achievements.rescan",
    "profileCreate": "profile.create",
    "profileUpdate": "profile.update",
    "profileActivate": "profile.activate",
    "profileDelete": "profile.delete",
    "configUpdate": "config.update",
    "configImport": "config.import",
    "environmentDelete": "environment.delete",
    "systemRestart": "system.restart",
    "systemRecover": "system.recover",
    "systemUpdate": "system.update",
    "kanbanCreate": "kanban.create",
    "kanbanUpdate": "kanban.update",
    "kanbanMove": "kanban.move",
    "kanbanDelete": "kanban.delete",
    "collaborationSelect": "collaboration.select",
    "collaborationCreate": "collaboration.create",
    "collaborationDelete": "collaboration.delete",
    "collaborationSend": "collaboration.send",
    "workflowSelect": "workflow.select",
    "workflowStart": "workflow.start",
    "workflowCancel": "workflow.cancel",
    "workflowRetry": "workflow.retry",
    "workflowApprove": "workflow.approve",
    "approvalSelect": "approval.select",
    "approvalApprove": "approval.approve",
    "approvalReject": "approval.reject",
    "runtimeSelect": "runtime.select",
    "runtimeCancel": "runtime.cancel",
    "runtimeRetry": "runtime.retry",
}

def is_route_action_payload(value: object) -> TypeGuard[dict[str, object]]:
    if not isinstance(value, dict) or not set(value).issubset(ACTION_PAYLOAD_FIELDS):
        return False
    for name, (kind, required) in ACTION_PAYLOAD_FIELDS.items():
        if required and name not in value:
            return False
        if name in value and not _matches_payload_type(value[name], kind):
            return False
    return True

def _matches_payload_type(value: object, kind: str) -> bool:
    if kind == "string":
        return isinstance(value, str)
    if kind == "boolean":
        return isinstance(value, bool)
    if kind == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if kind == "stringArray":
        return isinstance(value, list) and all(isinstance(item, str) for item in value)
    if kind == "stringMap":
        return isinstance(value, dict) and all(
            isinstance(key, str) and isinstance(item, str)
            for key, item in value.items()
        )
    return False
