import { StyleSheet } from 'react-native';

import { WEBUI_FONT_FAMILIES } from '../../app/webui-fonts';

const BODY_REGULAR = 'HermesGoogle-IBMPlexSans-400-Normal';
const BODY_MEDIUM = 'HermesGoogle-IBMPlexSans-500-Normal';
const BODY_SEMIBOLD = 'HermesGoogle-IBMPlexSans-600-Normal';
const BODY_BOLD = 'HermesGoogle-IBMPlexSans-700-Normal';
const DISPLAY_BOLD = 'SpaceGrotesk_700Bold';
const MONO_REGULAR = 'HermesTerminal-JetBrainsMono-400-Normal';

export const styles = StyleSheet.create({
  root: { flex: 1, minHeight: 0, overflow: 'hidden' },
  chat: { flex: 1, flexDirection: 'row', minHeight: 0 },
  main: { flex: 1, minHeight: 0, overflow: 'hidden' },
  header: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'space-between', paddingBottom: 7 },
  heading: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 9, minWidth: 112 },
  headingCompact: { gap: 4, minWidth: 116 },
  navToggle: { alignItems: 'center', borderRadius: 8, borderWidth: 1, height: 28, justifyContent: 'center', width: 28 },
  headerAvatar: { alignItems: 'center', borderRadius: 14, height: 28, justifyContent: 'center', overflow: 'hidden', width: 28 },
  headerAvatarCompact: { borderRadius: 13, height: 26, width: 26 },
  avatarImage: { borderRadius: 18, height: '100%', width: '100%' },
  headingCopy: { flex: 1, minWidth: 0 },
  headingTitle: { fontFamily: DISPLAY_BOLD, fontSize: 15, lineHeight: 19 },
  headingTitleCompact: { fontSize: 12, lineHeight: 16 },
  headingSubtitle: { fontFamily: BODY_REGULAR, fontSize: 10, lineHeight: 14 },
  headerControls: { alignItems: 'center', flexDirection: 'row', gap: 4, justifyContent: 'flex-end' },
  collaborationHeaderInfo: { alignItems: 'center', flexDirection: 'row', flexShrink: 1, gap: 7, maxWidth: 184, minWidth: 0 },
  collaborationHeaderCount: { flexShrink: 1, fontFamily: BODY_REGULAR, fontSize: 10, lineHeight: 14 },
  collaborationHeaderConnection: { borderRadius: 4, height: 8, shadowColor: '#34C759', shadowOpacity: 0.5, shadowRadius: 3, width: 8 },
  gatewayStatuses: { gap: 2, justifyContent: 'center', width: 94 },
  gatewayStatusRow: { alignItems: 'center', flexDirection: 'row', gap: 4, height: 13, width: 94 },
  gatewayStatusDot: { borderRadius: 3, height: 6, width: 6 },
  gatewayStatusLabel: { flexShrink: 0, fontFamily: MONO_REGULAR, fontSize: 7.5, lineHeight: 10, width: 36 },
  gatewayStatusVersion: { flexShrink: 0, fontFamily: MONO_REGULAR, fontSize: 7.5, lineHeight: 10, textAlign: 'left', width: 42 },
  modelTools: { alignItems: 'center', borderRadius: 8, borderWidth: 1, height: 32, justifyContent: 'center', paddingHorizontal: 7 },
  modelToolsText: { fontFamily: BODY_BOLD, fontSize: 9, lineHeight: 12 },
  liveDot: { borderRadius: 4, height: 8, marginHorizontal: 5, width: 8 },
  stream: { flex: 1, minHeight: 0 },
  streamContent: { flexGrow: 1, gap: 12, paddingTop: 16 },
  scrollToBottomWrap: { alignItems: 'center', left: 0, pointerEvents: 'box-none', position: 'absolute', right: 0, zIndex: 8 },
  scrollToBottom: { alignItems: 'center', borderRadius: 16, borderWidth: 1, height: 32, justifyContent: 'center', shadowColor: '#000000', shadowOffset: { height: 2, width: 0 }, shadowOpacity: 0.1, shadowRadius: 6, width: 32 },
  collaborationLiftNotice: { alignItems: 'center', alignSelf: 'center', borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 12, justifyContent: 'space-between', maxWidth: 820, minHeight: 58, paddingHorizontal: 13, paddingVertical: 10, width: '96%' },
  collaborationLiftCopy: { flex: 1, gap: 2, minWidth: 0 },
  collaborationLiftTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  collaborationLiftStateDot: { borderRadius: 4, height: 8, width: 8 },
  collaborationLiftTitle: { fontFamily: BODY_SEMIBOLD, fontSize: 12, lineHeight: 17 },
  collaborationLiftMeta: { fontFamily: BODY_REGULAR, fontSize: 9.5, lineHeight: 14 },
  collaborationLiftDots: { alignItems: 'center', flexDirection: 'row', gap: 3, marginLeft: 1 },
  collaborationAvatarStack: { alignItems: 'center', flexDirection: 'row', flexShrink: 0, paddingRight: 1 },
  collaborationAvatarStackItem: { borderRadius: 14, borderWidth: 2, height: 28, overflow: 'hidden', width: 28 },
  collaborationStatusBar: { alignItems: 'center', alignSelf: 'center', flexDirection: 'row', gap: 6, maxWidth: 920, minHeight: 28, paddingHorizontal: 12, width: '100%' },
  collaborationStatusDots: { alignItems: 'center', flexDirection: 'row', gap: 2 },
  collaborationStatusText: { flex: 1, fontFamily: BODY_REGULAR, fontSize: 12, lineHeight: 17 },
  emptyStream: { alignItems: 'center', justifyContent: 'center' },
  welcome: { alignItems: 'center', maxWidth: 480, paddingHorizontal: 24 },
  welcomeOrb: { marginBottom: 16 },
  welcomeTitle: { fontFamily: DISPLAY_BOLD, fontSize: 21, lineHeight: 29, textAlign: 'center' },
  welcomeBody: { fontFamily: BODY_REGULAR, fontSize: 13, lineHeight: 21, marginTop: 7, textAlign: 'center' },
  message: { alignItems: 'flex-start', flexDirection: 'row', gap: 9, maxWidth: '96%' },
  agentMessage: { alignSelf: 'flex-start' },
  messageEnvelope: { maxWidth: '96%' },
  agentMessageEnvelope: { alignSelf: 'flex-start', width: '96%' },
  userMessageEnvelope: { alignItems: 'flex-end', alignSelf: 'flex-end', maxWidth: '88%' },
  messageRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 9, maxWidth: '100%', paddingVertical: 2 },
  userMessageRow: { flexDirection: 'row-reverse' },
  messageAvatar: { alignItems: 'center', borderRadius: 9, flexShrink: 0, height: 30, justifyContent: 'center', marginTop: 2, overflow: 'hidden', position: 'relative', width: 30 },
  messageAvatarCompact: { height: 24, marginTop: 0, width: 24 },
  hermesAvatar: { backgroundColor: 'transparent' },
  messageStack: { alignItems: 'flex-start', flexShrink: 1, maxWidth: '88%', minWidth: 0 },
  userMessageStack: { alignItems: 'flex-end', maxWidth: '82%' },
  messageMeta: { alignItems: 'center', flexDirection: 'row', gap: 5, marginBottom: 3, marginHorizontal: 3, minHeight: 16 },
  userMessageMeta: { alignSelf: 'flex-end' },
  senderMeta: { alignItems: 'center', flexDirection: 'row', flexShrink: 1, gap: 5 },
  userSenderMeta: { flexShrink: 0 },
  messageName: { flexShrink: 1, fontFamily: BODY_BOLD, fontSize: 11, lineHeight: 15 },
  roleLabel: { flexShrink: 1, fontFamily: BODY_SEMIBOLD, fontSize: 9, fontStyle: 'italic', lineHeight: 13 },
  messageTime: { flexShrink: 0, fontFamily: BODY_REGULAR, fontSize: 8.5, lineHeight: 12, opacity: 0.6 },
  messageBody: { borderRadius: 8, borderWidth: 1, maxWidth: '100%', minWidth: 38, overflow: 'hidden', paddingHorizontal: 11, paddingTop: 9 },
  agentMessageBody: { borderTopLeftRadius: 3 },
  userMessageBody: { borderTopRightRadius: 3 },
  messageFooter: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginTop: 2, width: '100%' },
  userMessageFooter: { alignSelf: 'flex-end', justifyContent: 'flex-end' },
  messageActions: { alignItems: 'center', flexDirection: 'row', gap: 2, marginHorizontal: 2, minHeight: 26 },
  userMessageActions: { alignSelf: 'flex-end' },
  messageAction: { alignItems: 'center', borderRadius: 5, height: 26, justifyContent: 'center', width: 28 },
  pendingDots: { alignItems: 'center', flexDirection: 'row', gap: 4, minHeight: 16 },
  pendingDot: { borderRadius: 3, height: 5, width: 5 },
  pendingElapsed: { fontFamily: MONO_REGULAR, fontSize: 10, lineHeight: 14 },
  activityGroup: { gap: 4, maxWidth: 520, width: '100%' },
  todoSection: { borderRadius: 8, borderWidth: 1, gap: 6, maxWidth: 520, padding: 8, width: '100%' },
  todoHeader: { alignItems: 'center', flexDirection: 'row', gap: 6 },
  todoHeaderTitle: { fontFamily: BODY_SEMIBOLD, fontSize: 10, letterSpacing: 0.4, lineHeight: 14, textTransform: 'uppercase' },
  todoCount: { fontFamily: MONO_REGULAR, fontSize: 9, lineHeight: 13, marginLeft: 'auto' },
  todoList: { gap: 4 },
  todoRow: { alignItems: 'center', flexDirection: 'row', gap: 7, minHeight: 20 },
  todoTitle: { flex: 1, fontFamily: BODY_REGULAR, fontSize: 12, lineHeight: 17 },
  todoRunningDot: { borderRadius: 3, height: 6, width: 6 },
  activitySummary: { alignItems: 'center', flexDirection: 'row', gap: 6, minHeight: 24, paddingHorizontal: 3, paddingVertical: 2 },
  activityTitle: { flexShrink: 1, fontFamily: BODY_MEDIUM, fontSize: 11, lineHeight: 15 },
  activityCount: { fontFamily: MONO_REGULAR, fontSize: 9, lineHeight: 13 },
  activityTimeline: { gap: 4, paddingBottom: 4 },
  subagentCards: { gap: 6, paddingBottom: 2 },
  subagentCard: { borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, gap: 4, paddingHorizontal: 10, paddingVertical: 8, width: '100%' },
  subagentHeader: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  subagentIcon: { alignItems: 'center', borderRadius: 5, height: 22, justifyContent: 'center', width: 22 },
  subagentName: { flex: 1, fontFamily: BODY_SEMIBOLD, fontSize: 11.5, lineHeight: 16, minWidth: 0 },
  subagentStatus: { flexShrink: 0, fontFamily: BODY_MEDIUM, fontSize: 9, lineHeight: 13, textTransform: 'uppercase' },
  subagentTiming: { flexShrink: 0, fontFamily: MONO_REGULAR, fontSize: 8.5, lineHeight: 12 },
  subagentSummary: { fontFamily: BODY_REGULAR, fontSize: 11, lineHeight: 16 },
  subagentSummaryLabel: { fontFamily: BODY_SEMIBOLD, fontSize: 8.5, letterSpacing: 0.5, lineHeight: 12, opacity: 0.7, textTransform: 'uppercase' },
  teamStatusBar: { alignItems: 'center', alignSelf: 'center', borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 7, marginBottom: 10, maxWidth: 920, paddingHorizontal: 12, paddingVertical: 6, width: '100%' },
  teamStatusText: { flex: 1, fontFamily: BODY_MEDIUM, fontSize: 11, lineHeight: 15 },
  choiceOptions: { gap: 6, marginTop: 8 },
  choiceOption: { alignItems: 'center', borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 8, paddingHorizontal: 10, paddingVertical: 8 },
  choiceOptionKey: { fontFamily: BODY_BOLD, fontSize: 12, lineHeight: 16 },
  choiceOptionLabel: { flex: 1, fontFamily: BODY_REGULAR, fontSize: 12, lineHeight: 16 },
  choiceCustomRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 8 },
  choiceCustomInput: { borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, flex: 1, fontFamily: BODY_REGULAR, fontSize: 12, lineHeight: 16, minHeight: 34, paddingHorizontal: 10, paddingVertical: 7 },
  choiceCustomSend: { alignItems: 'center', borderRadius: 8, height: 34, justifyContent: 'center', paddingHorizontal: 14 },
  fileChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 4 },
  fileChip: { borderRadius: 5, fontFamily: MONO_REGULAR, fontSize: 9, lineHeight: 13, overflow: 'hidden', paddingHorizontal: 5, paddingVertical: 2 },
  rosterToggle: { borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, marginLeft: 'auto', paddingHorizontal: 8, paddingVertical: 3 },
  rosterToggleText: { fontFamily: BODY_MEDIUM, fontSize: 10, lineHeight: 14 },
  rosterPanel: { borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, gap: 4, marginTop: 6, padding: 8, width: '100%' },
  rosterRow: { alignItems: 'center', flexDirection: 'row', gap: 6, minHeight: 20 },
  rosterDot: { borderRadius: 3, height: 6, width: 6 },
  rosterName: { flex: 1, fontFamily: BODY_MEDIUM, fontSize: 11, lineHeight: 15, minWidth: 0 },
  rosterState: { flexShrink: 0, fontFamily: BODY_REGULAR, fontSize: 10, lineHeight: 14 },
  contextRing: { alignItems: 'center', borderRadius: 13, borderWidth: StyleSheet.hairlineWidth, height: 26, justifyContent: 'center', width: 26 },
  contextRingText: { fontFamily: MONO_REGULAR, fontSize: 8, lineHeight: 10 },
  contextRingLabel: { fontFamily: BODY_REGULAR, fontSize: 7, lineHeight: 9 },
  turnPhaseChip: { alignItems: 'center', borderRadius: 5, flexDirection: 'row', flexShrink: 0, gap: 4, maxWidth: 168, paddingHorizontal: 6, paddingVertical: 2 },
  turnPhaseDot: { borderRadius: 3, height: 6, width: 6 },
  turnPhaseLabel: { flexShrink: 1, fontFamily: BODY_SEMIBOLD, fontSize: 9, lineHeight: 13 },
  reasoningActivityDetail: { opacity: 0.85 },
  composer: { paddingTop: 7 },
  voiceError: { alignSelf: 'center', fontFamily: BODY_REGULAR, fontSize: 11, lineHeight: 15, marginBottom: 5, maxWidth: 920, paddingHorizontal: 8, width: '100%' },
  attachmentStrip: { alignSelf: 'center', marginBottom: 8, maxHeight: 76, maxWidth: 920, width: '100%' },
  attachmentStripContent: { gap: 10, paddingHorizontal: 7, paddingTop: 7 },
  attachmentItem: { borderRadius: 13, height: 64, position: 'relative' },
  attachmentSurface: { borderRadius: 13, borderWidth: StyleSheet.hairlineWidth },
  attachmentImageItem: { overflow: 'visible', width: 64 },
  attachmentFileItem: { width: 224 },
  attachmentImagePreview: { borderRadius: 12, height: 62, overflow: 'hidden', width: 62 },
  attachmentThumbnail: { height: '100%', width: '100%' },
  attachmentFilePreview: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 10, paddingHorizontal: 10, paddingRight: 30 },
  attachmentFileIcon: { alignItems: 'center', height: 40, justifyContent: 'center', width: 36 },
  attachmentFileCopy: { flex: 1, minWidth: 0 },
  attachmentName: { fontFamily: BODY_MEDIUM, fontSize: 13, lineHeight: 17 },
  attachmentSize: { fontFamily: BODY_REGULAR, fontSize: 11, lineHeight: 15, marginTop: 2 },
  attachmentRemove: { alignItems: 'center', height: 30, justifyContent: 'center', position: 'absolute', right: -8, top: -8, width: 30, zIndex: 3 },
  attachmentRemoveFallback: { alignItems: 'center', backgroundColor: '#636366', borderRadius: 11, height: 22, justifyContent: 'center', width: 22 },
  storedAttachments: { gap: 6, marginTop: 10 },
  storedAttachment: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 38 },
  storedAttachmentCopy: { flex: 1, minWidth: 0 },
  storedAttachmentName: { fontFamily: BODY_MEDIUM, fontSize: 12, lineHeight: 16 },
  storedAttachmentSize: { fontFamily: BODY_REGULAR, fontSize: 10, lineHeight: 13 },
  inputShellShadow: { alignSelf: 'center', borderRadius: 27, maxWidth: 920, shadowOffset: { height: 2, width: 0 }, shadowOpacity: 0.22, shadowRadius: 4, width: '100%' },
  inputShell: { borderRadius: 27, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'column', minHeight: 104, overflow: 'hidden', position: 'relative', width: '100%' },
  openMinisSlashPopup: { alignSelf: 'center', borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, height: 224, marginBottom: 8, maxWidth: 920, overflow: 'hidden', shadowOffset: { height: 2, width: 0 }, shadowOpacity: 0.14, shadowRadius: 8, width: '100%' },
  openMinisSlashScroll: { flex: 1 },
  openMinisSlashRow: { justifyContent: 'center', minHeight: 54, paddingHorizontal: 12, paddingVertical: 7 },
  openMinisSlashCommand: { fontFamily: BODY_SEMIBOLD, fontSize: 13, lineHeight: 17 },
  openMinisSlashDescription: { fontFamily: BODY_REGULAR, fontSize: 11, lineHeight: 15, marginTop: 2 },
  openMinisSlashEmpty: { height: 224, justifyContent: 'center', paddingHorizontal: 12 },
  openMinisAttachmentViewport: { maxHeight: 160, paddingTop: 8 },
  openMinisAttachmentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 16, paddingTop: 6 },
  openMinisInput: { backgroundColor: 'transparent', borderColor: 'transparent', borderWidth: 0, fontSize: 16, letterSpacing: 0, lineHeight: 22, maxHeight: 120, minHeight: 54, outlineColor: 'transparent', outlineStyle: 'solid', outlineWidth: 0, paddingBottom: 8, paddingHorizontal: 16, paddingTop: 16, textAlignVertical: 'top' },
  openMinisVoiceInput: { gap: 6, minHeight: 78, paddingBottom: 10, paddingHorizontal: 16, paddingTop: 8 },
  openMinisVoiceTopRow: { alignItems: 'center', flexDirection: 'row', minHeight: 24 },
  openMinisVoiceStatus: { flex: 1, fontFamily: BODY_MEDIUM, fontSize: 11, lineHeight: 15 },
  openMinisVoiceCancel: { alignItems: 'center', height: 28, justifyContent: 'center', width: 28 },
  openMinisWaveform: { alignItems: 'center', flexDirection: 'row', gap: 4, height: 32, justifyContent: 'center', width: '100%' },
  openMinisWaveBar: { borderRadius: 2, minHeight: 6, width: 3 },
  openMinisTranscript: { fontFamily: BODY_REGULAR, fontSize: 13, lineHeight: 18, maxHeight: 72, textAlign: 'center' },
  openMinisToolbar: { alignItems: 'center', flexDirection: 'row', gap: 4, minHeight: 46, paddingBottom: 7, paddingHorizontal: 8 },
  openMinisToolbarSpacer: { flex: 1, minWidth: 0 },
  openMinisRoundControl: { alignItems: 'center', borderRadius: 19, borderWidth: 0, height: 38, justifyContent: 'center', width: 38 },
  openMinisSendControl: { alignItems: 'center', borderRadius: 19, height: 38, justifyContent: 'center', marginLeft: 6, width: 38 },
  openMinisSendFallbackCircle: { alignItems: 'center', borderRadius: 19, height: 38, justifyContent: 'center', width: 38 },
  openMinisSendFallback: { fontFamily: BODY_SEMIBOLD, fontSize: 17, lineHeight: 20, textAlign: 'center' },
  history: { borderRightWidth: 1, minWidth: 220, paddingHorizontal: 12, paddingVertical: 14, width: 260 },
  historyModal: { borderRightWidth: 0, flex: 1, paddingTop: 18, width: '100%' },
  pageSidebarNav: { borderBottomWidth: StyleSheet.hairlineWidth, gap: 9, paddingBottom: 10 },
  pageSidebarActions: { flexDirection: 'row', gap: 2 },
  pageSidebarAction: { alignItems: 'center', borderRadius: 6, flex: 1, gap: 4, justifyContent: 'center', minHeight: 46 },
  pageSidebarActionText: { fontFamily: BODY_REGULAR, fontSize: 9 },
  historyBrand: { alignItems: 'center', flexDirection: 'row', gap: 11, paddingBottom: 4, paddingHorizontal: 4, paddingTop: 3 },
  roomIcon: { alignItems: 'center', backgroundColor: '#242424', borderRadius: 8, height: 38, justifyContent: 'center', width: 38 },
  roomIconText: { color: '#ffffff', fontFamily: DISPLAY_BOLD, fontSize: 16 },
  historyTitle: { fontFamily: DISPLAY_BOLD, fontSize: 14 },
  historyKicker: { fontFamily: MONO_REGULAR, fontSize: 8, letterSpacing: 1.1 },
  newChat: { alignItems: 'center', borderRadius: 10, minHeight: 38, justifyContent: 'center', paddingHorizontal: 12 },
  newChatText: { fontFamily: BODY_SEMIBOLD, fontSize: 12 },
  historyLabel: { fontFamily: MONO_REGULAR, fontSize: 9, letterSpacing: 1.2, marginTop: 12, paddingHorizontal: 8 },
  historyList: { gap: 3, paddingBottom: 12, paddingTop: 8 },
  historyScroll: { flex: 1 },
  historyItem: { borderRadius: 9, gap: 7, paddingHorizontal: 10, paddingVertical: 9 },
  historyItemTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  historyItemTitle: { flex: 1, fontFamily: BODY_SEMIBOLD, fontSize: 12, minWidth: 0 },
  historyItemTime: { fontFamily: BODY_REGULAR, fontSize: 9 },
  historyItemProfileRow: { alignItems: 'center', flexDirection: 'row', gap: 6 },
  historyItemMeta: { flexShrink: 1, fontFamily: BODY_REGULAR, fontSize: 9 },
  historyActiveDot: { borderRadius: 4, height: 7, marginLeft: 'auto', width: 7 },
  historySearchWrap: { paddingHorizontal: 4, paddingTop: 10 },
  historySearchInput: { borderRadius: 6, borderWidth: 1, fontFamily: BODY_REGULAR, fontSize: 12, height: 38, paddingHorizontal: 10 },
  historyFooter: { alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'space-between', minHeight: 36, paddingHorizontal: 8 },
  drawerRoot: { flex: 1 },
  drawerBackdrop: { backgroundColor: 'rgba(0,0,0,0.60)', right: 256 },
  drawer: { borderLeftWidth: 1, bottom: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0, width: 256 },
  drawerHeader: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 56, paddingHorizontal: 20 },
  drawerTitle: { fontFamily: WEBUI_FONT_FAMILIES.MondwestRegular, fontSize: 18, letterSpacing: 0.84, lineHeight: 17 },
  drawerClose: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  drawerContent: { gap: 12, paddingBottom: 12, paddingHorizontal: 4, paddingTop: 8 },
  drawerNewChat: { alignSelf: 'stretch', justifyContent: 'flex-start', marginHorizontal: 0 },
  drawerCard: { borderRadius: 8, borderWidth: 1, marginHorizontal: 0, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 10 },
  drawerCardRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  drawerCardCopy: { flex: 1, minWidth: 0 },
  drawerLabel: { fontFamily: WEBUI_FONT_FAMILIES.RulesExpandedRegular, fontSize: 10, letterSpacing: 1.1, lineHeight: 14 },
  drawerDetail: { fontFamily: BODY_REGULAR, fontSize: 10, lineHeight: 14, marginTop: 2 },
  modelPicker: { alignItems: 'center', flexDirection: 'row', gap: 4, marginTop: 2 },
  modelName: { flex: 1, fontFamily: BODY_MEDIUM, fontSize: 13, lineHeight: 18 },
  modelOptions: { borderTopWidth: 1, marginTop: 8, paddingTop: 5 },
  modelOption: { alignItems: 'center', flexDirection: 'row', minHeight: 34, paddingHorizontal: 2 },
  modelOptionText: { flex: 1, fontFamily: BODY_REGULAR, fontSize: 11 },
  reasoningCard: { borderRadius: 8, borderWidth: 1, marginHorizontal: 0, overflow: 'hidden' },
  reasoningTitle: { fontFamily: DISPLAY_BOLD, fontSize: 14, lineHeight: 20, padding: 12 },
  reasoningBody: { borderTopWidth: 1, padding: 12 },
});
