// Generated by scripts/generate-swiftui-route-actions.mjs. Do not edit.

let hermesRouteSnapshotVersion = 1

enum HermesRouteSnapshotField: String, CodingKey, CaseIterable {
  case version
  case route
  case sessions
  case sessionContext
  case sessionSidebarJSON
  case sessionProjectsJSON
  case sessionPullRequestsJSON
  case sessionStatsJSON
  case files
  case accountFilesJSON
  case managedFilesJSON
  case git
  case workflows
  case approvals
  case runtime
  case analytics
  case models
  case modelAuxiliary
  case modelMoa
  case modelMoaJSON
  case providerOauthJSON
  case providerOauthPendingJSON
  case credentialPoolJSON
  case customProviderEndpointsJSON
  case modelConfirmation
  case detectedModels
  case operation
  case logs
  case cron
  case cronBlueprintsJSON
  case cronDeliveryTargetsJSON
  case cronRunsJSON
  case skills
  case toolsets
  case terminalBackendsJSON
  case computerUseJSON
  case skillHubSourcesJSON
  case learningGraphJSON
  case skillHubResultJSON
  case integrations
  case mcpServersJSON
  case channelOnboardingJSON
  case installations
  case pairing
  case achievements
  case collaboration
  case kanban
  case kanbanMetaJSON
  case kanbanDetailJSON
  case profiles
  case botRelayJSON
  case botPetJSON
  case botRoutinesJSON
  case config
  case environment
  case system
  case systemHooksJSON
  case memory
}

struct HermesRouteActionPayload: Encodable, Equatable {
  let route: String
  let id: String?
  let name: String?
  let value: String?
  let detail: String?
  let targetId: String?
  let enabled: Bool?
  let position: Int?
  let requestId: String?
  let fields: [String: String]?
  let uris: [String]?

  init(
    route: String,
    id: String? = nil,
    name: String? = nil,
    value: String? = nil,
    detail: String? = nil,
    targetId: String? = nil,
    enabled: Bool? = nil,
    position: Int? = nil,
    requestId: String? = nil,
    fields: [String: String]? = nil,
    uris: [String]? = nil
  ) {
    self.route = route
    self.id = id
    self.name = name
    self.value = value
    self.detail = detail
    self.targetId = targetId
    self.enabled = enabled
    self.position = position
    self.requestId = requestId
    self.fields = fields
    self.uris = uris
  }
}

enum HermesRouteAction: String, CaseIterable {
  case refresh = "route.refresh"
  case sessionSelect = "session.select"
  case sessionOpen = "session.open"
  case sessionDelete = "session.delete"
  case sessionRename = "session.rename"
  case sessionCompress = "session.compress"
  case sessionFork = "session.fork"
  case sessionExport = "session.export"
  case sessionArchive = "session.archive"
  case sessionPin = "session.pin"
  case sessionUnread = "session.unread"
  case sessionBulkDelete = "session.bulk-delete"
  case sessionImport = "session.import"
  case sessionProjects = "session.projects"
  case sessionPullRequests = "session.pull-requests"
  case sessionDeleteEmpty = "session.delete-empty"
  case fileSelect = "file.select"
  case fileDelete = "file.delete"
  case fileDownload = "file.download"
  case fileShare = "file.share"
  case fileImport = "file.import"
  case fileQuery = "files.query"
  case folderCreate = "folder.create"
  case managedFilesOpen = "files.managed.open"
  case managedFileDownload = "files.managed.download"
  case managedFileDelete = "files.managed.delete"
  case managedFileImport = "files.managed.import"
  case modelSelect = "model.select"
  case modelSelectCancel = "model.select.cancel"
  case modelDiscover = "model.discover"
  case modelSave = "model.save"
  case modelTest = "model.test"
  case modelMoaSave = "model.moa.save"
  case providerOauthStart = "provider.oauth.start"
  case providerOauthSubmit = "provider.oauth.submit"
  case providerOauthCancel = "provider.oauth.cancel"
  case credentialPoolAdd = "credential.pool.add"
  case credentialPoolDelete = "credential.pool.delete"
  case customEndpointValidate = "provider.custom.validate"
  case customEndpointSave = "provider.custom.save"
  case customEndpointActivate = "provider.custom.activate"
  case customEndpointDelete = "provider.custom.delete"
  case logsFilter = "logs.filter"
  case cronCreate = "cron.create"
  case cronUpdate = "cron.update"
  case cronToggle = "cron.toggle"
  case cronRun = "cron.run"
  case cronDelete = "cron.delete"
  case cronBlueprintCreate = "cron.blueprint.create"
  case skillCreate = "skill.create"
  case skillToggle = "skill.toggle"
  case skillSelect = "skill.select"
  case skillView = "skill.view"
  case skillUpdate = "skill.update"
  case skillHubUpdate = "skillhub.update"
  case skillHubSearch = "skillhub.search"
  case skillHubPreview = "skillhub.preview"
  case skillHubScan = "skillhub.scan"
  case skillHubInstall = "skillhub.install"
  case skillHubUninstall = "skillhub.uninstall"
  case learningGraphRefresh = "learning.graph.refresh"
  case toolsetToggle = "toolset.toggle"
  case toolsetProvider = "toolset.provider"
  case toolsetModel = "toolset.model"
  case toolsetEnvironment = "toolset.environment"
  case toolsetPostSetup = "toolset.post-setup"
  case terminalBackend = "terminal.backend"
  case computerUseGrant = "computer-use.grant"
  case installationRollback = "installation.rollback"
  case pluginRescan = "plugin.rescan"
  case pluginInstall = "plugin.install"
  case pluginUpdate = "plugin.update"
  case pluginDelete = "plugin.delete"
  case pluginVisibility = "plugin.visibility"
  case integrationCreate = "integration.create"
  case integrationUpdate = "integration.update"
  case integrationToggle = "integration.toggle"
  case integrationTest = "integration.test"
  case integrationDelete = "integration.delete"
  case channelOnboardingStart = "channel.onboarding.start"
  case channelOnboardingRefresh = "channel.onboarding.refresh"
  case channelOnboardingApply = "channel.onboarding.apply"
  case channelOnboardingCancel = "channel.onboarding.cancel"
  case webhooksEnable = "webhooks.enable"
  case mcpTest = "mcp.test"
  case mcpAuth = "mcp.auth"
  case mcpReplace = "mcp.replace"
  case mcpCatalogInstall = "mcp.catalog.install"
  case pairingApprove = "pairing.approve"
  case pairingRevoke = "pairing.revoke"
  case pairingClearPending = "pairing.clear-pending"
  case achievementsRescan = "achievements.rescan"
  case profileCreate = "profile.create"
  case profileUpdate = "profile.update"
  case profileRename = "profile.rename"
  case profileDescription = "profile.description"
  case profileModel = "profile.model"
  case profileAutoDescribe = "profile.auto-describe"
  case profileSetup = "profile.setup"
  case profileExport = "profile.export"
  case profileActivate = "profile.activate"
  case profileDelete = "profile.delete"
  case botChatOpen = "bot.chat.open"
  case botGroupsOpen = "bot.groups.open"
  case botMetaUpdate = "bot.meta.update"
  case botProfileDescribe = "bot.profile.describe"
  case botProfileConfigure = "bot.profile.configure"
  case botAvatarUpload = "bot.avatar.upload"
  case botAvatarGenerate = "bot.avatar.generate"
  case botAvatarClear = "bot.avatar.clear"
  case botPetSelect = "bot.pet.select"
  case botRelaySend = "bot.relay.send"
  case configUpdate = "config.update"
  case configImport = "config.import"
  case environmentDelete = "environment.delete"
  case environmentSet = "environment.set"
  case environmentReveal = "environment.reveal"
  case systemRestart = "system.restart"
  case systemRecover = "system.recover"
  case systemUpdate = "system.update"
  case systemStart = "system.start"
  case systemStop = "system.stop"
  case systemDrain = "system.drain"
  case systemUpdateCheck = "system.update.check"
  case systemDoctor = "system.doctor"
  case systemSecurityAudit = "system.security-audit"
  case systemBackup = "system.backup"
  case systemBackupImport = "system.backup.import"
  case systemHookCreate = "system.hook.create"
  case systemHookDelete = "system.hook.delete"
  case systemDebugShare = "system.debug-share"
  case systemDiagnostics = "system.diagnostics"
  case systemCheckpoints = "system.checkpoints"
  case systemCheckpointPrune = "system.checkpoints.prune"
  case systemCuratorRun = "system.curator.run"
  case systemCuratorPause = "system.curator.pause"
  case memoryProvider = "memory.provider"
  case memoryOAuthStart = "memory.oauth.start"
  case memoryConfigUpdate = "memory.config.update"
  case memoryReset = "memory.reset"
  case kanbanCreate = "kanban.create"
  case kanbanUpdate = "kanban.update"
  case kanbanMove = "kanban.move"
  case kanbanDelete = "kanban.delete"
  case kanbanTaskOpen = "kanban.task.open"
  case kanbanCommentAdd = "kanban.comment.add"
  case kanbanAttachmentUpload = "kanban.attachment.upload"
  case kanbanAttachmentDownload = "kanban.attachment.download"
  case kanbanRelationLink = "kanban.relation.link"
  case kanbanRelationUnlink = "kanban.relation.unlink"
  case kanbanDispatch = "kanban.dispatch"
  case kanbanReassign = "kanban.reassign"
  case kanbanReclaim = "kanban.reclaim"
  case kanbanSpecify = "kanban.specify"
  case kanbanDecompose = "kanban.decompose"
  case kanbanRunInspect = "kanban.run.inspect"
  case kanbanRunTerminate = "kanban.run.terminate"
  case kanbanTaskLog = "kanban.task.log"
  case kanbanBoardSwitch = "kanban.board.switch"
  case collaborationSelect = "collaboration.select"
  case collaborationCreate = "collaboration.create"
  case collaborationDelete = "collaboration.delete"
  case collaborationSend = "collaboration.send"
  case workflowSelect = "workflow.select"
  case workflowStart = "workflow.start"
  case workflowCancel = "workflow.cancel"
  case workflowRetry = "workflow.retry"
  case workflowApprove = "workflow.approve"
  case approvalSelect = "approval.select"
  case approvalApprove = "approval.approve"
  case approvalReject = "approval.reject"
  case runtimeSelect = "runtime.select"
  case runtimeCancel = "runtime.cancel"
  case runtimeRetry = "runtime.retry"
  case gitSelect = "git.select"
  case gitStage = "git.stage"
  case gitUnstage = "git.unstage"
  case gitRevert = "git.revert"
  case gitCommit = "git.commit"
  case gitPush = "git.push"
  case gitSwitchBranch = "git.branch.switch"
  case gitRefresh = "git.refresh"
  case gitGhAuth = "git.gh-auth"
  case gitFileDiff = "git.file-diff"
  case gitCommitContext = "git.commit-context"
  case gitRevParse = "git.rev-parse"
  case gitPullRequests = "git.pull-requests"
  case gitCreatePR = "git.create-pr"
  case gitAddWorktree = "git.worktree.add"
  case gitRemoveWorktree = "git.worktree.remove"
}
