import Foundation
import SwiftUI

private let hermesAccountFilesPageLimit = 50

private enum HermesAccountFileSource: String, CaseIterable, Identifiable {
  case all
  case modelOutput = "model_output"
  case userUpload = "user_upload"

  var id: String { rawValue }
}

private struct HermesAccountFilesQuerySnapshot: Decodable, Equatable {
  let dateFrom: String?
  let dateTo: String?
  let keyword: String?
  let source: String?
}

private struct HermesAccountFilesPageSnapshot: Decodable, Equatable {
  let files: [HermesFileSnapshot]
  let hasMore: Bool
  let limit: Int
  let nextOffset: Int
  let offset: Int
  let query: HermesAccountFilesQuerySnapshot
  let requestId: String
  let total: Int

  static func decode(_ json: String?) -> Self? {
    guard let json, let data = json.data(using: .utf8) else { return nil }
    return try? JSONDecoder().decode(Self.self, from: data)
  }
}

private struct HermesAccountFileSection: Identifiable {
  let id: String
  let files: [HermesFileSnapshot]
  let timestamp: Double
}

struct HermesAccountFilesPagedContent: View {
  @EnvironmentObject private var appearance: HermesAppearanceModel
  let chinese: Bool
  let initialFiles: [HermesFileSnapshot]
  let pageJSON: String?
  let onAction: HermesRouteActionSink
  let onImport: () -> Void
  let onCreateFolder: () -> Void

  @State private var files: [HermesFileSnapshot] = []
  @State private var filterByDate = false
  @State private var hasReceivedPage = false
  @State private var isLoading = false
  @State private var nextOffset = 0
  @State private var requestId = ""
  @State private var search = ""
  @State private var searchTask: Task<Void, Never>?
  @State private var selectedDate = Date()
  @State private var source = HermesAccountFileSource.all
  @State private var total = 0

  private var displayedFiles: [HermesFileSnapshot] {
    hasReceivedPage ? files : initialFiles
  }

  private var sections: [HermesAccountFileSection] {
    Dictionary(grouping: displayedFiles) {
      $0.dateLabel ?? (chinese ? "未知日期" : "Unknown Date")
    }
    .map { label, entries in
      HermesAccountFileSection(
        id: label,
        files: entries.sorted { ($0.createdAt ?? 0) > ($1.createdAt ?? 0) },
        timestamp: entries.map { $0.createdAt ?? 0 }.max() ?? 0
      )
    }
    .sorted { $0.timestamp > $1.timestamp }
  }

  var body: some View {
    List {
      if displayedFiles.isEmpty {
        ContentUnavailableView(
          LocalizedStringKey(
            isLoading
              ? (chinese ? "正在搜索云端文件" : "Searching Cloud Files")
              : (search.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                ? (chinese ? "暂无云端文件" : "No Cloud Files")
                : (chinese ? "没有匹配的文件" : "No Matching Files"))
          ),
          systemImage: isLoading ? "arrow.triangle.2.circlepath" : "doc.text.magnifyingglass"
        )
      }
      ForEach(sections) { section in
        Section(section.id) {
          ForEach(section.files) { file in
            Button {
              guard file.status == "available" else { return }
              onAction(
                .fileDownload,
                HermesRouteActionPayload(route: "files", id: file.id, name: file.name)
              )
            } label: {
              HStack(spacing: 12) {
                Image(systemName: symbol(for: file))
                  .foregroundStyle(file.source == "model_output" ? appearance.palette.accent : appearance.palette.primary)
                  .frame(width: 26)
                VStack(alignment: .leading, spacing: 3) {
                  Text(file.name).font(HermesFonts.bodyBold(15))
                  Text(file.detail)
                    .font(HermesFonts.body(11))
                    .foregroundStyle(appearance.palette.secondary)
                  Label(
                    file.source == "model_output"
                      ? (chinese ? "Hermes 生成" : "Generated by Hermes")
                      : (chinese ? "用户上传" : "Uploaded by User"),
                    systemImage: file.source == "model_output" ? "sparkles" : "person.crop.circle"
                  )
                  .font(HermesFonts.body(10))
                  .foregroundStyle(appearance.palette.secondary)
                }
                Spacer()
                if file.status == "uploading" {
                  ProgressView().controlSize(.small)
                } else if file.status == "failed" {
                  Image(systemName: "exclamationmark.circle.fill")
                    .foregroundStyle(appearance.palette.destructive)
                } else {
                  Image(systemName: "chevron.right")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(appearance.palette.secondary.opacity(0.6))
                }
              }
              .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            .swipeActions {
              Button(role: .destructive) {
                onAction(.fileDelete, HermesRouteActionPayload(route: "files", id: file.id))
              } label: {
                Label(chinese ? "删除" : "Delete", systemImage: "trash")
              }
              if file.status == "available" {
                Button {
                  onAction(
                    .fileShare,
                    HermesRouteActionPayload(route: "files", id: file.id, name: file.name)
                  )
                } label: {
                  Label(chinese ? "分享" : "Share", systemImage: "square.and.arrow.up")
                }
                .tint(appearance.palette.primary)
              }
            }
          }
        }
      }
      if nextOffset < total {
        Section {
          Button {
            requestPage(offset: nextOffset)
          } label: {
            HStack {
              Spacer()
              if isLoading { ProgressView().controlSize(.small) }
              Label(chinese ? "加载更多" : "Load more", systemImage: "arrow.down.circle")
              Spacer()
            }
          }
          .disabled(isLoading)
        } footer: {
          Text(chinese
            ? "已加载 \(displayedFiles.count) / \(total) 个文件"
            : "Loaded \(displayedFiles.count) of \(total) files")
        }
      }
    }
    .hermesListStyle()
    .background(appearance.palette.background)
    .searchable(text: $search, prompt: chinese ? "搜索全部云端文件" : "Search all cloud files")
    .refreshable { requestPage(offset: 0) }
    .toolbar {
      ToolbarItemGroup(placement: .navigationBarTrailing) {
        Menu {
          Picker(chinese ? "来源" : "Source", selection: $source) {
            Text(chinese ? "全部" : "All").tag(HermesAccountFileSource.all)
            Text(chinese ? "用户上传" : "User Uploads").tag(HermesAccountFileSource.userUpload)
            Text(chinese ? "模型生成" : "Model Outputs").tag(HermesAccountFileSource.modelOutput)
          }
          Toggle(chinese ? "按日期筛选" : "Filter by Date", isOn: $filterByDate)
          if filterByDate {
            DatePicker(chinese ? "日期" : "Date", selection: $selectedDate, displayedComponents: .date)
          }
        } label: {
          Label(chinese ? "筛选" : "Filter", systemImage: "line.3.horizontal.decrease.circle")
        }
        Button(action: onImport) {
          Label(chinese ? "导入文件" : "Import file", systemImage: "square.and.arrow.down")
        }
        Button(action: onCreateFolder) {
          Label(chinese ? "新建文件夹" : "New folder", systemImage: "folder.badge.plus")
        }
      }
    }
    .onAppear { applyPageJSON() }
    .onChange(of: pageJSON) { _, _ in applyPageJSON() }
    .onChange(of: search) { _, _ in scheduleFirstPage() }
    .onChange(of: source) { _, _ in requestPage(offset: 0) }
    .onChange(of: filterByDate) { _, _ in requestPage(offset: 0) }
    .onChange(of: selectedDate) { _, _ in
      if filterByDate { requestPage(offset: 0) }
    }
    .onDisappear { searchTask?.cancel() }
  }

  private func scheduleFirstPage() {
    searchTask?.cancel()
    searchTask = Task {
      try? await Task.sleep(nanoseconds: 350_000_000)
      guard !Task.isCancelled else { return }
      await MainActor.run { requestPage(offset: 0) }
    }
  }

  private func requestPage(offset: Int) {
    let nextRequestId = "account-files-\(UUID().uuidString.lowercased())"
    requestId = nextRequestId
    isLoading = true
    if offset == 0 {
      hasReceivedPage = true
      files = []
      nextOffset = 0
      total = 0
    }
    var fields = [
      "limit": String(hermesAccountFilesPageLimit),
      "offset": String(max(0, offset)),
    ]
    let keyword = normalizedSearch
    if !keyword.isEmpty { fields["q"] = keyword }
    if source != .all { fields["source"] = source.rawValue }
    if filterByDate {
      let day = serverDate(selectedDate)
      fields["dateFrom"] = day
      fields["dateTo"] = day
    }
    onAction(
      .fileQuery,
      HermesRouteActionPayload(
        route: "files",
        requestId: nextRequestId,
        fields: fields
      )
    )
    Task {
      try? await Task.sleep(nanoseconds: 30_000_000_000)
      guard !Task.isCancelled else { return }
      await MainActor.run {
        if requestId == nextRequestId { isLoading = false }
      }
    }
  }

  private func applyPageJSON() {
    guard let page = HermesAccountFilesPageSnapshot.decode(pageJSON) else { return }
    if !page.requestId.isEmpty && page.requestId != requestId { return }
    if !queryMatches(page.query) {
      if page.requestId.isEmpty { requestPage(offset: 0) }
      return
    }
    if page.offset == 0 {
      files = page.files
    } else {
      var merged: [String: HermesFileSnapshot] = [:]
      for file in files { merged[file.id] = file }
      for file in page.files { merged[file.id] = file }
      files = merged.values.sorted { ($0.createdAt ?? 0) > ($1.createdAt ?? 0) }
    }
    hasReceivedPage = true
    isLoading = false
    nextOffset = page.nextOffset
    total = page.total
  }

  private func queryMatches(_ query: HermesAccountFilesQuerySnapshot) -> Bool {
    let expectedSource = source == .all ? nil : source.rawValue
    let expectedDate = filterByDate ? serverDate(selectedDate) : nil
    return (query.keyword ?? "") == normalizedSearch
      && query.source == expectedSource
      && query.dateFrom == expectedDate
      && query.dateTo == expectedDate
  }

  private var normalizedSearch: String {
    search.trimmingCharacters(in: .whitespacesAndNewlines)
  }

  private func serverDate(_ date: Date) -> String {
    let parts = Calendar(identifier: .gregorian).dateComponents([.year, .month, .day], from: date)
    return String(format: "%04d-%02d-%02d", parts.year ?? 0, parts.month ?? 0, parts.day ?? 0)
  }

  private func symbol(for file: HermesFileSnapshot) -> String {
    switch file.fileType {
    case "image": "photo"
    case "video": "film"
    case "audio": "waveform"
    case "archive": "archivebox"
    case "code": "chevron.left.forwardslash.chevron.right"
    case "document": "doc.text"
    default: "doc"
    }
  }
}
