// Generated by scripts/generate-swiftui-route-actions.mjs. Do not edit.
export const HERMES_SWIFTUI_ROUTE_SNAPSHOT_VERSION = 1 as const;

export const HERMES_SWIFTUI_ROUTE_SNAPSHOT_FIELDS = [
  'version',
  'route',
  'sessions',
  'sessionContext',
  'files',
  'workflows',
  'approvals',
  'runtime',
  'analytics',
  'models',
  'modelAuxiliary',
  'modelMoa',
  'modelConfirmation',
  'detectedModels',
  'operation',
  'logs',
  'cron',
  'skills',
  'integrations',
  'installations',
  'pairing',
  'achievements',
  'collaboration',
  'kanban',
  'profiles',
  'config',
  'environment',
  'system',
  'memory',
] as const;

export const HERMES_SWIFTUI_ROUTE_ACTION_PAYLOAD_FIELDS = [
  'route',
  'id',
  'name',
  'value',
  'detail',
  'targetId',
  'enabled',
  'position',
  'requestId',
  'fields',
  'uris',
] as const;

export interface HermesSwiftUIRouteActionPayload {
  route: string;
  id?: string;
  name?: string;
  value?: string;
  detail?: string;
  targetId?: string;
  enabled?: boolean;
  position?: number;
  requestId?: string;
  fields?: Readonly<Record<string, string>>;
  uris?: readonly string[];
}

const actionPayloadFieldNames = new Set<string>(HERMES_SWIFTUI_ROUTE_ACTION_PAYLOAD_FIELDS);

export function isHermesSwiftUIRouteActionPayload(
  value: unknown,
): value is HermesSwiftUIRouteActionPayload {
  if (!isGeneratedRecord(value)) return false;
  if (Object.keys(value).some((field) => !actionPayloadFieldNames.has(field))) return false;
  if (!(typeof value.route === 'string')) return false;
  if (value.id !== undefined && !(typeof value.id === 'string')) return false;
  if (value.name !== undefined && !(typeof value.name === 'string')) return false;
  if (value.value !== undefined && !(typeof value.value === 'string')) return false;
  if (value.detail !== undefined && !(typeof value.detail === 'string')) return false;
  if (value.targetId !== undefined && !(typeof value.targetId === 'string')) return false;
  if (value.enabled !== undefined && !(typeof value.enabled === 'boolean')) return false;
  if (value.position !== undefined && !(typeof value.position === 'number' && Number.isInteger(value.position))) return false;
  if (value.requestId !== undefined && !(typeof value.requestId === 'string')) return false;
  if (value.fields !== undefined && !(isGeneratedRecord(value.fields) && Object.values(value.fields).every((entry) => typeof entry === 'string'))) return false;
  if (value.uris !== undefined && !(Array.isArray(value.uris) && value.uris.every((entry) => typeof entry === 'string'))) return false;
  return true;
}

function isGeneratedRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export const HERMES_SWIFTUI_ROUTE_ACTIONS = {
  refresh: 'route.refresh',
  sessionSelect: 'session.select',
  sessionOpen: 'session.open',
  sessionDelete: 'session.delete',
  sessionRename: 'session.rename',
  sessionCompress: 'session.compress',
  sessionFork: 'session.fork',
  fileSelect: 'file.select',
  fileDelete: 'file.delete',
  fileDownload: 'file.download',
  fileShare: 'file.share',
  fileImport: 'file.import',
  folderCreate: 'folder.create',
  modelSelect: 'model.select',
  modelSelectCancel: 'model.select.cancel',
  modelDiscover: 'model.discover',
  modelSave: 'model.save',
  modelTest: 'model.test',
  logsFilter: 'logs.filter',
  cronCreate: 'cron.create',
  cronToggle: 'cron.toggle',
  cronRun: 'cron.run',
  cronDelete: 'cron.delete',
  skillCreate: 'skill.create',
  skillToggle: 'skill.toggle',
  skillSelect: 'skill.select',
  skillView: 'skill.view',
  skillUpdate: 'skill.update',
  installationRollback: 'installation.rollback',
  pluginRescan: 'plugin.rescan',
  pluginInstall: 'plugin.install',
  pluginUpdate: 'plugin.update',
  pluginDelete: 'plugin.delete',
  pluginVisibility: 'plugin.visibility',
  integrationCreate: 'integration.create',
  integrationUpdate: 'integration.update',
  integrationToggle: 'integration.toggle',
  integrationDelete: 'integration.delete',
  mcpTest: 'mcp.test',
  mcpCatalogInstall: 'mcp.catalog.install',
  pairingApprove: 'pairing.approve',
  pairingRevoke: 'pairing.revoke',
  pairingClearPending: 'pairing.clear-pending',
  achievementsRescan: 'achievements.rescan',
  profileCreate: 'profile.create',
  profileUpdate: 'profile.update',
  profileActivate: 'profile.activate',
  profileDelete: 'profile.delete',
  configUpdate: 'config.update',
  configImport: 'config.import',
  environmentDelete: 'environment.delete',
  systemRestart: 'system.restart',
  systemRecover: 'system.recover',
  systemUpdate: 'system.update',
  systemStart: 'system.start',
  systemStop: 'system.stop',
  systemDrain: 'system.drain',
  systemUpdateCheck: 'system.update.check',
  memoryProvider: 'memory.provider',
  memoryReset: 'memory.reset',
  kanbanCreate: 'kanban.create',
  kanbanUpdate: 'kanban.update',
  kanbanMove: 'kanban.move',
  kanbanDelete: 'kanban.delete',
  collaborationSelect: 'collaboration.select',
  collaborationCreate: 'collaboration.create',
  collaborationDelete: 'collaboration.delete',
  collaborationSend: 'collaboration.send',
  workflowSelect: 'workflow.select',
  workflowStart: 'workflow.start',
  workflowCancel: 'workflow.cancel',
  workflowRetry: 'workflow.retry',
  workflowApprove: 'workflow.approve',
  approvalSelect: 'approval.select',
  approvalApprove: 'approval.approve',
  approvalReject: 'approval.reject',
  runtimeSelect: 'runtime.select',
  runtimeCancel: 'runtime.cancel',
  runtimeRetry: 'runtime.retry',
} as const;
