// Generated by scripts/sync-native-fonts.py. Do not edit.
export const GENERATED_NATIVE_FONT_FACES = [
  {
    "source": "tracked-ui",
    "cssFamily": "Collapse",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "Collapse-Bold",
    "assetFile": "Collapse-Bold.otf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Collapse",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "Collapse",
    "assetFile": "Collapse-Regular.otf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Mondwest",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "Mondwest",
    "assetFile": "Mondwest-Regular.ttf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Rules Compressed",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "Rules Compressed-Medium",
    "assetFile": "RulesCompressed-Medium.ttf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Rules Compressed",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "Rules Compressed",
    "assetFile": "RulesCompressed-Regular.ttf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Rules Expanded",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "Rules Expanded-Bold",
    "assetFile": "RulesExpanded-Bold.ttf"
  },
  {
    "source": "tracked-ui",
    "cssFamily": "Rules Expanded",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "Rules Expanded",
    "assetFile": "RulesExpanded-Regular.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Inter",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Inter-400-Normal",
    "assetFile": "Google-Inter-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Inter",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Inter-500-Normal",
    "assetFile": "Google-Inter-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Inter",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Inter-600-Normal",
    "assetFile": "Google-Inter-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Inter",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Inter-700-Normal",
    "assetFile": "Google-Inter-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Sans",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexSans-400-Normal",
    "assetFile": "Google-IBMPlexSans-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Sans",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexSans-500-Normal",
    "assetFile": "Google-IBMPlexSans-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Sans",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexSans-600-Normal",
    "assetFile": "Google-IBMPlexSans-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Sans",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexSans-700-Normal",
    "assetFile": "Google-IBMPlexSans-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Work Sans",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-WorkSans-400-Normal",
    "assetFile": "Google-WorkSans-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Work Sans",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-WorkSans-500-Normal",
    "assetFile": "Google-WorkSans-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Work Sans",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-WorkSans-600-Normal",
    "assetFile": "Google-WorkSans-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Work Sans",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-WorkSans-700-Normal",
    "assetFile": "Google-WorkSans-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Atkinson Hyperlegible",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-AtkinsonHyperlegible-400-Normal",
    "assetFile": "Google-AtkinsonHyperlegible-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Atkinson Hyperlegible",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-AtkinsonHyperlegible-700-Normal",
    "assetFile": "Google-AtkinsonHyperlegible-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Sans",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMSans-400-Normal",
    "assetFile": "Google-DMSans-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Sans",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMSans-500-Normal",
    "assetFile": "Google-DMSans-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Sans",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMSans-600-Normal",
    "assetFile": "Google-DMSans-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Sans",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMSans-700-Normal",
    "assetFile": "Google-DMSans-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Spectral",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Spectral-400-Normal",
    "assetFile": "Google-Spectral-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Spectral",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Spectral-500-Normal",
    "assetFile": "Google-Spectral-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Spectral",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Spectral-600-Normal",
    "assetFile": "Google-Spectral-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Spectral",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Spectral-700-Normal",
    "assetFile": "Google-Spectral-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Fraunces",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Fraunces-400-Normal",
    "assetFile": "Google-Fraunces-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Fraunces",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Fraunces-500-Normal",
    "assetFile": "Google-Fraunces-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Fraunces",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-Fraunces-600-Normal",
    "assetFile": "Google-Fraunces-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Source Serif 4",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SourceSerif4-400-Normal",
    "assetFile": "Google-SourceSerif4-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Source Serif 4",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SourceSerif4-500-Normal",
    "assetFile": "Google-SourceSerif4-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Source Serif 4",
    "weight": 600,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SourceSerif4-600-Normal",
    "assetFile": "Google-SourceSerif4-600-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Source Serif 4",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SourceSerif4-700-Normal",
    "assetFile": "Google-SourceSerif4-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "JetBrains Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-JetBrainsMono-400-Normal",
    "assetFile": "Google-JetBrainsMono-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "JetBrains Mono",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-JetBrainsMono-500-Normal",
    "assetFile": "Google-JetBrainsMono-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "JetBrains Mono",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-JetBrainsMono-700-Normal",
    "assetFile": "Google-JetBrainsMono-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexMono-400-Normal",
    "assetFile": "Google-IBMPlexMono-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Mono",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexMono-500-Normal",
    "assetFile": "Google-IBMPlexMono-500-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "IBM Plex Mono",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-IBMPlexMono-700-Normal",
    "assetFile": "Google-IBMPlexMono-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Space Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SpaceMono-400-Normal",
    "assetFile": "Google-SpaceMono-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Space Mono",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-SpaceMono-700-Normal",
    "assetFile": "Google-SpaceMono-700-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "Share Tech Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-ShareTechMono-400-Normal",
    "assetFile": "Google-ShareTechMono-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMMono-400-Normal",
    "assetFile": "Google-DMMono-400-Normal.ttf"
  },
  {
    "source": "google",
    "cssFamily": "DM Mono",
    "weight": 500,
    "style": "normal",
    "runtimeFamily": "HermesGoogle-DMMono-500-Normal",
    "assetFile": "Google-DMMono-500-Normal.ttf"
  },
  {
    "source": "tracked-terminal",
    "cssFamily": "JetBrains Mono",
    "weight": 400,
    "style": "normal",
    "runtimeFamily": "HermesTerminal-JetBrainsMono-400-Normal",
    "assetFile": "Terminal-JetBrainsMono-400-Normal.ttf"
  },
  {
    "source": "tracked-terminal",
    "cssFamily": "JetBrains Mono",
    "weight": 400,
    "style": "italic",
    "runtimeFamily": "HermesTerminal-JetBrainsMono-400-Italic",
    "assetFile": "Terminal-JetBrainsMono-400-Italic.ttf"
  },
  {
    "source": "tracked-terminal",
    "cssFamily": "JetBrains Mono",
    "weight": 700,
    "style": "normal",
    "runtimeFamily": "HermesTerminal-JetBrainsMono-700-Normal",
    "assetFile": "Terminal-JetBrainsMono-700-Normal.ttf"
  }
] as const;
